FROM python:3.9@sha256:da5aee29682d12a6649f51c8d6f15b87deb3e6c524b923c41d0cb3304d07c913
EXPOSE 8392

WORKDIR /app

# Reuses the pythonasync-uvloop lock file; this app needs a subset of it
COPY internal/test/integration/components/pythonasync-uvloop/requirements-3.9.txt .
RUN pip install --require-hashes -r requirements-3.9.txt

COPY internal/test/integration/components/pythonasync-generic .

CMD ["python", "async_server_test.py"]
